#include "protocol_items.h" // IWYU pragma: keep

const SubGhzProtocol* const subghz_protocol_registry_items[] = {
    &subghz_protocol_gate_tx,
    &subghz_protocol_keeloq,
    &subghz_protocol_nice_flo,
    &subghz_protocol_came,
    &subghz_protocol_faac_slh,
    &subghz_protocol_nice_flor_s,
    &subghz_protocol_came_twee,
    &subghz_protocol_came_atomo,
    &subghz_protocol_nero_sketch,
    &subghz_protocol_ido,
    &subghz_protocol_hormann,
    &subghz_protocol_nero_radio,
    &subghz_protocol_somfy_telis,
    &subghz_protocol_somfy_keytis,
    &subghz_protocol_princeton,
    &subghz_protocol_raw,
    &subghz_protocol_linear,
    &subghz_protocol_secplus_v2,
    &subghz_protocol_secplus_v1,
    &subghz_protocol_megacode,
    &subghz_protocol_holtek,
    &subghz_protocol_chamb_code,
    &subghz_protocol_power_smart,
    &subghz_protocol_marantec,
    &subghz_protocol_bett,
    &subghz_protocol_doitrand,
    &subghz_protocol_phoenix_v2,
    &subghz_protocol_honeywell_wdb,
    &subghz_protocol_magellan,
    &subghz_protocol_intertechno_v3,
    &subghz_protocol_clemsa,
    &subghz_protocol_ansonic,
    &subghz_protocol_smc5326,
    &subghz_protocol_holtek_th12x,
    &subghz_protocol_linear_delta3,
    &subghz_protocol_dooya,
    &subghz_protocol_alutech_at_4n,
    &subghz_protocol_kinggates_stylo_4k,
    // &ws_protocol_infactory,
    // &ws_protocol_thermopro_tx4,
    // &ws_protocol_nexus_th,
    // &ws_protocol_gt_wt_02,
    // &ws_protocol_gt_wt_03,
    // &ws_protocol_acurite_606tx,
    // &ws_protocol_acurite_609txc,
    // &ws_protocol_acurite_986,
    // &ws_protocol_bresser_3ch, // Should be before lacrosse
    // &ws_protocol_lacrosse_tx,
    // &ws_protocol_lacrosse_tx141thbv2,
    // &ws_protocol_oregon2,
    // &ws_protocol_oregon3,
    // &ws_protocol_acurite_592txr,
    // &ws_protocol_ambient_weather,
    // &ws_protocol_solight_te44, // Should be before auriol
    // &ws_protocol_auriol_th,
    // &ws_protocol_oregon_v1,
    // &ws_protocol_tx_8300,
    // &ws_protocol_wendox_w6726,
    // &ws_protocol_auriol_ahfl,
    // &ws_protocol_kedsum_th,
    // &ws_protocol_emose601x,
    // &ws_protocol_acurite_5n1,
    // &ws_protocol_vauno_en8822c,
    // &subghz_protocol_pocsag,
    // &tpms_protocol_schrader_gg4,
    &subghz_protocol_bin_raw,
    &subghz_protocol_mastercode,
    // &subghz_protocol_x10,
    // &subghz_protocol_hormann_bisecur,
    &subghz_protocol_legrand,
    &subghz_protocol_dickert_mahs,
    &subghz_protocol_gangqi,
    &subghz_protocol_marantec24,
    &subghz_protocol_hollarm,
    &subghz_protocol_hay21,
    &subghz_protocol_revers_rb2,
    &subghz_protocol_feron,
    &subghz_protocol_roger,
    // ARF Custom edition: automotive protocols (sorted alphabetically)
    &subghz_protocol_bmw_cas4,
    &subghz_protocol_chrysler,
    &subghz_protocol_fiat_marelli,
    &subghz_protocol_fiat_spa,
    &subghz_protocol_ford_v0,
    &ford_protocol_v1,
    &ford_protocol_v2,
    &ford_protocol_v3,
    &subghz_protocol_gm_rolling,
    &honda_static_protocol,
    &subghz_protocol_kia_v0,
    &subghz_protocol_kia_v1,
    &subghz_protocol_kia_v2,
    &subghz_protocol_kia_v3_v4,
    &subghz_protocol_kia_v5,
    &subghz_protocol_kia_v6,
    &subghz_protocol_kia_v7,
    &subghz_protocol_land_rover_v0,
    &subghz_protocol_mazda_siemens,
    &subghz_protocol_mazda_v0,
    &subghz_protocol_mitsubishi_v0,
    &subghz_protocol_nissan,
    &subghz_protocol_porsche_cayenne,
    &subghz_protocol_psa,
    &subghz_protocol_psa2,
    &subghz_protocol_renault,
    &subghz_protocol_scher_khan,
    &subghz_protocol_sheriff_cfm,
    &subghz_protocol_star_line,
    &subghz_protocol_subaru,
    &subghz_protocol_suzuki,
    &subghz_protocol_toyota,
    &subghz_protocol_vag,
};

const SubGhzProtocolRegistry subghz_protocol_registry = {
    .items = subghz_protocol_registry_items,
    .size = COUNT_OF(subghz_protocol_registry_items)};
