#!/usr/bin/env python3
"""
Patch Flipper about.c to support selectable custom passport characters.

Injects:
  - Include for desktop_settings.h (to read passport_char setting)
  - A shuka_passport_get_icon() helper that picks icons by char + mood + variant
  - Replaces direct I_passport_*_46x49 icon arrays/uses with our helper

Characters: 0=dolphin (default), 1=skull, 2=hacker, 3=robot
"""

import sys, os, glob

# ── Locate about.c ────────────────────────────────────────────────────────────
CANDIDATES = [
    "flipper-fw/applications/settings/about/about.c",
    "flipper-fw/applications/about/about.c",
    "flipper-fw/applications/settings/passport/passport.c",
    "flipper-fw/applications/main/about/about.c",
]

path = None
for c in CANDIDATES:
    if os.path.exists(c):
        path = c
        break

if path is None:
    found = glob.glob("flipper-fw/**/about.c", recursive=True)
    if found:
        path = found[0]

if path is None:
    print("ERROR: about.c not found in flipper-fw — skipping passport patch", file=sys.stderr)
    sys.exit(0)  # Non-fatal: don't break the build if the file layout changed

print(f"Patching: {path}")

with open(path, "r") as f:
    src = f.read()

# Already patched? (idempotency guard)
if "shuka_passport_get_icon" in src:
    print("Already patched — skipping")
    sys.exit(0)

# ── Verify the file contains passport icons (sanity check) ───────────────────
if "passport_happy1_46x49" not in src:
    print("WARNING: passport_happy1_46x49 not found in about.c — ARF may have moved passport code", file=sys.stderr)
    print("Skipping passport patch to avoid breaking the build", file=sys.stderr)
    sys.exit(0)

# ── Relative path from about.c to desktop_settings.h ────────────────────────
about_dir = os.path.dirname(path)
desktop_settings_h = "flipper-fw/applications/services/desktop/desktop_settings.h"
if os.path.exists(desktop_settings_h):
    rel = os.path.relpath(desktop_settings_h, about_dir)
else:
    rel = "../../../services/desktop/desktop_settings.h"

# ── Inject block ──────────────────────────────────────────────────────────────
# Added right after the first #include block in the file
INJECT = f"""
// ── ARF-Shuka: selectable passport characters ────────────────────────────────
#include "{rel}"

// Character 0 = dolphin (built-in), 1 = skull, 2 = hacker, 3 = robot
// Icons for chars 1-3 are generated by generate_passport_chars.py and compiled
// from assets/icons/Passport/{{}}<char>_<mood>N_46x49.png

extern const Icon I_skull_happy1_46x49;
extern const Icon I_skull_happy2_46x49;
extern const Icon I_skull_happy3_46x49;
extern const Icon I_skull_okay1_46x49;
extern const Icon I_skull_okay2_46x49;
extern const Icon I_skull_okay3_46x49;
extern const Icon I_skull_bad1_46x49;
extern const Icon I_skull_bad2_46x49;
extern const Icon I_skull_bad3_46x49;

extern const Icon I_hacker_happy1_46x49;
extern const Icon I_hacker_happy2_46x49;
extern const Icon I_hacker_happy3_46x49;
extern const Icon I_hacker_okay1_46x49;
extern const Icon I_hacker_okay2_46x49;
extern const Icon I_hacker_okay3_46x49;
extern const Icon I_hacker_bad1_46x49;
extern const Icon I_hacker_bad2_46x49;
extern const Icon I_hacker_bad3_46x49;

extern const Icon I_robot_happy1_46x49;
extern const Icon I_robot_happy2_46x49;
extern const Icon I_robot_happy3_46x49;
extern const Icon I_robot_okay1_46x49;
extern const Icon I_robot_okay2_46x49;
extern const Icon I_robot_okay3_46x49;
extern const Icon I_robot_bad1_46x49;
extern const Icon I_robot_bad2_46x49;
extern const Icon I_robot_bad3_46x49;

static const Icon* shuka_passport_get_icon(uint8_t mood, uint8_t variant) {{
    // mood: 0=happy, 1=okay, 2=bad   variant: 0-2
    DesktopSettings _sp_settings = {{0}};
    desktop_settings_load(&_sp_settings);
    uint8_t ch = _sp_settings.passport_char;

    static const Icon* skull_icons[3][3] = {{
        {{&I_skull_happy1_46x49, &I_skull_happy2_46x49, &I_skull_happy3_46x49}},
        {{&I_skull_okay1_46x49,  &I_skull_okay2_46x49,  &I_skull_okay3_46x49}},
        {{&I_skull_bad1_46x49,   &I_skull_bad2_46x49,   &I_skull_bad3_46x49}},
    }};
    static const Icon* hacker_icons[3][3] = {{
        {{&I_hacker_happy1_46x49, &I_hacker_happy2_46x49, &I_hacker_happy3_46x49}},
        {{&I_hacker_okay1_46x49,  &I_hacker_okay2_46x49,  &I_hacker_okay3_46x49}},
        {{&I_hacker_bad1_46x49,   &I_hacker_bad2_46x49,   &I_hacker_bad3_46x49}},
    }};
    static const Icon* robot_icons[3][3] = {{
        {{&I_robot_happy1_46x49, &I_robot_happy2_46x49, &I_robot_happy3_46x49}},
        {{&I_robot_okay1_46x49,  &I_robot_okay2_46x49,  &I_robot_okay3_46x49}},
        {{&I_robot_bad1_46x49,   &I_robot_bad2_46x49,   &I_robot_bad3_46x49}},
    }};

    uint8_t m = (mood < 3) ? mood : 0;
    uint8_t v = (variant < 3) ? variant : 0;

    if(ch == 1) return skull_icons[m][v];
    if(ch == 2) return hacker_icons[m][v];
    if(ch == 3) return robot_icons[m][v];
    return NULL; // 0 = dolphin: caller uses original I_passport_* icons
}}
// ─────────────────────────────────────────────────────────────────────────────
"""

# Insert the inject block right after the last top-level #include line
import re
last_include = -1
for m in re.finditer(r'^#include\s+[<"].+[">]', src, re.MULTILINE):
    last_include = m.end()

if last_include == -1:
    print("WARNING: no #include found in about.c — prepending inject block")
    src = INJECT + src
else:
    src = src[:last_include] + "\n" + INJECT + src[last_include:]

# ── Patch all icon array initializers to use our helper when ch != 0 ─────────
#
# Pattern we're looking for (one or more variants):
#   &I_passport_happy1_46x49
#   &I_passport_happy2_46x49
#   &I_passport_happy3_46x49
# etc.
#
# Strategy: find every *static* or local const Icon* array that references
# passport icons and wrap the whole thing in a shuka_passport_get_icon check.
#
# Since ARF's code varies, we use a targeted replacement:
# Find any function/block that contains a canvas_draw_icon with a passport icon
# and prepend a "if char != dolphin, use shuka_passport_get_icon" path.

# ── Map mood names used in identifiers ────────────────────────────────────────
MOOD_MAP = {"happy": 0, "okay": 1, "bad": 2}

def patch_canvas_draw_icon(src):
    """
    Find:
        canvas_draw_icon(canvas, x, y, &I_passport_<mood>N_46x49);
    and replace with a conditional that uses shuka_passport_get_icon.

    Also handles when the icon is in a local variable:
        const Icon* icon = &I_passport_happy1_46x49;
        canvas_draw_icon(canvas, x, y, icon);
    """
    changed = False

    # Replace direct references: &I_passport_<mood><n>_46x49
    # with: shuka_get or original icon based on passport_char
    # We can't easily inline this without knowing variable scope,
    # so we wrap the WHOLE draw icon call.

    # Pattern: canvas_draw_icon(canvas, <x>, <y>, &I_passport_<mood><n>_46x49);
    def replace_direct(m):
        nonlocal changed
        x_arg = m.group(1)
        y_arg = m.group(2)
        mood  = m.group(3)  # happy/okay/bad
        n     = int(m.group(4)) - 1  # 0-indexed variant
        midx  = MOOD_MAP.get(mood, 0)
        orig  = m.group(0)
        changed = True
        return (
            f"do {{ "
            f"const Icon* _sp_icon = shuka_passport_get_icon({midx}, {n}); "
            f"canvas_draw_icon(canvas, {x_arg}, {y_arg}, "
            f"_sp_icon ? _sp_icon : &I_passport_{mood}{n+1}_46x49); "
            f"}} while(0)"
        )

    pattern_direct = (
        r"canvas_draw_icon\s*\(\s*canvas\s*,\s*"
        r"([^,]+),\s*([^,]+),\s*"
        r"&I_passport_(happy|okay|bad)([123])_46x49\s*\)"
    )
    src_new = re.sub(pattern_direct, replace_direct, src)
    if src_new != src:
        src = src_new
        changed = True
        print("Patched: canvas_draw_icon with direct passport icon reference")

    return src, changed

src, c1 = patch_canvas_draw_icon(src)

# ── Also patch const Icon* arrays ─────────────────────────────────────────────
# Pattern:
#   const Icon* happy_icons[] = {&I_passport_happy1_46x49, ...};
#   const Icon* icon = happy_icons[idx];
#   canvas_draw_icon(canvas, x, y, icon);
#
# This is too complex to patch generically without knowing variable names.
# Instead, patch the icon pointer ASSIGNMENT when it references passport icons.

def replace_icon_ptr(m):
    mood = m.group(1)  # happy/okay/bad
    n    = int(m.group(2)) - 1
    midx = MOOD_MAP.get(mood, 0)
    orig_icon = f"&I_passport_{mood}{n+1}_46x49"
    return (
        f"(shuka_passport_get_icon({midx}, {n}) "
        f"? shuka_passport_get_icon({midx}, {n}) "
        f": {orig_icon})"
    )

pattern_ptr = r"&I_passport_(happy|okay|bad)([123])_46x49"
src_new = re.sub(pattern_ptr, replace_icon_ptr, src)
if src_new != src:
    src = src_new
    print("Patched: inline passport icon pointer references")

with open(path, "w") as f:
    f.write(src)

print("about.c passport patch applied OK")
